name: Packages
on: push
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: [self-hosted]
    steps:
    - run: whoami
    - run: pwd
    - name: Checkout
      uses: actions/checkout@v1
      with:
        repository: hbfernandes/my-app
        ref: master
        path: pipelines
    - name: Build
      uses: hbfernandes/actions/maven@published
      with:
        args: clean        
        
