name: Packages
on: release
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        repository: hbfernandes/my-app
        ref: master
        path: pipelines
    - name: Cache
      uses: actions/cache@v1
      with:
        path: .m2/repository
        key: mvn-${{ hashFiles('**/pom.xml') }}
    - name: Build
      uses: hbfernandes/actions/maven@master
      with:
        args: deploy
        