name: Packages
on: push
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: [self-hosted]
    steps:
    - run: pwd
    - run: whoami
    - name: Checkout
      uses: actions/checkout@v1
      with:
        repository: hbfernandes/my-app
        ref: master
        
        
