name: Test
# on: repository_dispatch
on: release

env:
  MVN_CACHE_PATH: ${{ github.workspace }}/cache
  MVN_WORSPACE_PATH: ${{ github.workspace }}/project

jobs:
  my-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: hbfernandes/my-app
          ref: master
          token: ${{ secrets.SCM_TOKEN }}
          path: pipelines/project
      - name: Build
        uses: hbfernandes/actions/mvn@master
        with:
          args: clean install

    # name: A job to say hello
    # steps:
    #   - name: Build
    #     uses: hbfernandes/actions/mvn@master
    #     id: hello
    #     # with:
    #     #   args: ''
      

        